### ISSUE TITLE
Load time when more 2k triggers

### ISSUE THREAD

**Issue by giacomodeliberali** [maikebing/SilkierQuartz#57]
Hi, do you have any plan to speed up load time or use some sort of pagination/lazy loading? The app is awsome, but when thousends of triggers are registred in the database, the UI starts to become unresponsive. Any suggestions on how to quickly work around this issue?

**Comment by maikebing** [comment]
That's a problem.

**Comment by zihotki** [comment]
I stumbled upon similar issue and here are my findings. Unfortunately due to the implementation details of Quartz.net that's going to be a pain in the ass to implement. The project uses helpers from Quartz.net and the helpers don't support paging. So in order to implement support for that new helpers or data layer (EF based or anything else) is needed.
